// experiments/solid1/src/test.tsx
import assert from "node:assert/strict"
import { existsSync, statSync, unlinkSync } from "node:fs"
import { For, createSignal } from "solid-js"
import {
  createTestRoot,
  hasNativeTestRenderer,
} from "@jhomra21/gpuix-solid1"
import { Solid1CompatibilityLab } from "./app"

const screenshotPath = "/tmp/gpuix-solid1-compatibility.png"

function PointerReleaseRecoveryFixture() {
  const [generation, setGeneration] = createSignal(0)
  const [dragging, setDragging] = createSignal(false)
  const [remounted, setRemounted] = createSignal(false)
  const [releases, setReleases] = createSignal(0)

  return (
    <div style={{ width: 320, height: 120, padding: 12 }}>
      <For each={[generation()]}>
        {(currentGeneration) => (
          <div
            testId="pointer-release-target"
            onPointerDown={() => setDragging(true)}
            onPointerMove={() => {
              if (!dragging() || remounted()) return
              setRemounted(true)
              setGeneration((value) => value + 1)
            }}
            onPointerUp={() => {
              setDragging(false)
              setReleases((value) => value + 1)
            }}
            onPointerCancel={() => setDragging(false)}
            style={{ width: 240, height: 64, backgroundColor: "#202533" }}
          >
            <text>{`Pointer target ${currentGeneration}`}</text>
          </div>
        )}
      </For>
      <text testId="pointer-generation">{generation()}</text>
      <text testId="pointer-release-count">{releases()}</text>
    </div>
  )
}

if (!hasNativeTestRenderer) {
  console.log("solid1 compatibility: native TestGpuixRenderer unavailable; skipped")
  process.exit(0)
}

if (existsSync(screenshotPath)) unlinkSync(screenshotPath)
const testRoot = createTestRoot()
testRoot.render(() => <Solid1CompatibilityLab />)

try {
  const { renderer } = testRoot
  assert.equal(renderer.textContent("runtime-version"), "solid-js 1.9.15 → shared GPUI host kernel")
  assert.equal(renderer.textContent("count-value"), "0")

  renderer.clickTestId("increment")
  renderer.clickTestId("increment")
  assert.equal(renderer.textContent("count-value"), "2")

  renderer.typeTestId("name-input", "Ada")
  assert.equal(renderer.textContent("greeting"), "Hello Ada")

  assert.equal(renderer.hasTestId("details-panel"), false)
  renderer.clickTestId("toggle-details")
  assert.equal(renderer.hasTestId("details-panel"), true)
  renderer.clickTestId("toggle-details")
  assert.equal(renderer.hasTestId("details-panel"), false)

  renderer.clickTestId("prepend-delta")
  assert.equal(renderer.textContent("item-list"), "DeltaAlphaBetaGamma")
  renderer.clickTestId("rotate-items")
  assert.equal(renderer.textContent("item-list"), "AlphaBetaGammaDelta")

  renderer.captureScreenshot(screenshotPath)
  assert.equal(existsSync(screenshotPath), true)
  assert.ok(statSync(screenshotPath).size > 0)

  console.log("solid1 compatibility: passed")
} finally {
  testRoot.unmount()
}

const pointerRoot = createTestRoot(360, 160)
pointerRoot.render(() => <PointerReleaseRecoveryFixture />)
try {
  const { renderer } = pointerRoot
  renderer.dragTestId("pointer-release-target", 40, 0)
  assert.equal(renderer.textContent("pointer-generation"), "1", "drag should replace the pressed retained target")
  const releasesAfterRemountDrag = Number(renderer.textContent("pointer-release-count"))

  renderer.clickCenterTestId("pointer-release-target")
  assert.equal(
    Number(renderer.textContent("pointer-release-count")),
    releasesAfterRemountDrag + 1,
    "stationary click after a drag/remount should deliver exactly one local pointer-up",
  )

  console.log("solid1 post-remount pointer release: passed")
} finally {
  pointerRoot.unmount()
}

// examples/counter/src/codeimage/test.tsx
import assert from "node:assert/strict"
import { existsSync, statSync, unlinkSync } from "node:fs"
import {
  createTestApp,
  createTestRoot,
  hasNativeTestRenderer,
} from "@jhomra21/gpuix-solid"
import { CodeImageNativeDemo } from "./app"

const screenshotPath = "/tmp/gpuix-solid-codeimage-native.png"

async function requireTestId(app: ReturnType<typeof createTestApp>, testId: string): Promise<void> {
  assert.equal(await app.getByTestId(testId).count(), 1, `expected ${testId} to exist exactly once`)
}

async function main(): Promise<void> {
  if (!hasNativeTestRenderer) {
    console.log("codeimage integration: native TestGpuixRenderer unavailable; skipped")
    return
  }

  if (existsSync(screenshotPath)) unlinkSync(screenshotPath)

  const testRoot = createTestRoot()
  testRoot.renderer.clockPause()
  testRoot.render(() => <CodeImageNativeDemo />)
  const app = createTestApp(testRoot.renderer)

  try {
    await requireTestId(app, "codeimage-shell")
    assert.equal(await app.getByTestId("preview-filename").textContent(), "native-renderer.tsx")
    assert.equal(await app.getByTestId("theme-label").textContent(), "Tokyo Night")
    assert.equal(await app.getByTestId("padding-value").textContent(), "48px")

    await app.clock.fastForward(400)
    const preview = await app.getByTestId("preview-frame").bounds()
    assert.ok(preview.width > 600)
    assert.ok(preview.height > 400)

    await requireTestId(app, "tool-theme")
    await app.getByTestId("tool-theme").click()
    await requireTestId(app, "theme-rose")
    await app.getByTestId("theme-rose").click()
    assert.equal(await app.getByTestId("theme-label").textContent(), "Rosé Pine")

    await requireTestId(app, "tool-frame")
    await app.getByTestId("tool-frame").click()
    await requireTestId(app, "padding-plus")
    await app.getByTestId("padding-plus").click()
    assert.equal(await app.getByTestId("padding-value").textContent(), "56px")
    await requireTestId(app, "chrome-compact")
    await app.getByTestId("chrome-compact").click()

    await requireTestId(app, "filename-input")
    await app.getByTestId("filename-input").fill("solid2-native.tsx")
    assert.equal(await app.getByTestId("preview-filename").textContent(), "solid2-native.tsx")

    await requireTestId(app, "tool-code")
    await app.getByTestId("tool-code").click()
    await requireTestId(app, "line-number-1")
    await requireTestId(app, "toggle-line-numbers")
    await app.getByTestId("toggle-line-numbers").click()
    assert.equal(await app.getByTestId("line-number-1").count(), 0)
    await requireTestId(app, "font-size-plus")
    await app.getByTestId("font-size-plus").click()
    assert.equal(await app.getByTestId("font-size-value").textContent(), "14px")

    await requireTestId(app, "export-button")
    await app.getByTestId("export-button").click()
    assert.match(await app.getByTestId("export-status").textContent(), /Exported 1 preview/)

    await app.screenshot({ path: screenshotPath })
    assert.equal(existsSync(screenshotPath), true)
    assert.ok(statSync(screenshotPath).size > 0)

    console.log("codeimage integration: passed")
  } finally {
    await app.clock.resume()
    await app.close()
    testRoot.unmount()
  }
}

await main()
